// Get all EMPLOYEES
export const ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST'
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const ALL_EMPLOYEES_FAIL = 'ALL_EMPLOYEES_FAIL'
export const ALL_EMPLOYEES_RESET = 'ALL_EMPLOYEES_RESET'