// Get all Employees
export const ALL_EMPLOYEES_REQUEST = 'ALL_EMPLOYEES_REQUEST'
export const ALL_EMPLOYEES_SUCCESS = 'ALL_EMPLOYEES_SUCCESS'
export const ALL_EMPLOYEES_FAIL = 'ALL_EMPLOYEES_FAIL'
export const ALL_EMPLOYEES_RESET = 'ALL_EMPLOYEES_RESET'

// create new ticket
export const CREATE_TICKET_REQUEST = 'CREATE_TICKET_REQUEST'
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKETSUCCESST'
export const CREATE_TICKET_FAIL = 'CREATE_TICKETFAILT'
export const TICKET_RESET = 'TICKET_RESET'

// Get all Tickets
export const ALL_TICKETS_REQUEST = 'ALL_TICKETS_REQUEST'
export const ALL_TICKETS_SUCCESS = 'ALL_TICKETS_SUCCESS'
export const ALL_TICKETS_FAIL = 'ALL_TICKETS_FAIL'
export const ALL_TICKETS_RESET = 'ALL_TICKETS_RESET'

// Ticket status
export const TICKET_STATUS_REQUEST = 'TICKET_STATUS_REQUEST'
export const TICKET_STATUS_SUCCESS = 'TICKET_STATUS_SUCCESS'
export const TICKET_STATUS_FAIL = 'TICKET_STATUS_FAIL'

// Assign ticket to employee
export const ASSIGN_TICKET_REQUEST = 'ASSIGN_TICKET_REQUEST'
export const ASSIGN_TICKET_SUCCESS = 'ASSIGN_TICKET_SUCCESS'
export const ASSIGN_TICKET_FAIL = 'ASSIGN_TICKET_FAIL'

// Get all tickets of employee
export const EMPLOYEE_TICKET_REQUEST = 'EMPLOYEE_TICKET_REQUEST'
export const EMPLOYEE_TICKET_SUCCESS = 'EMPLOYEE_TICKET_SUCCESS'
export const EMPLOYEE_TICKET_FAIL = 'EMPLOYEE_TICKET_FAIL'
export const EMPLOYEE_TICKET_RESET = 'EMPLOYEE_TICKET_RESET'